"""user_roles

Revision ID: 05aba5a740e5
Revises: 61109446c97b
Create Date: 2018-07-26 15:39:44.584306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05aba5a740e5'
down_revision = '61109446c97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###
