"""user table

Revision ID: 61109446c97b
Revises: 1cb3a8b2e581
Create Date: 2018-07-20 17:00:50.181192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61109446c97b'
down_revision = '1cb3a8b2e581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
